apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: booking
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "change-me"
  SPRING_DATASOURCE_PASSWORD: "change-me"
  STRIPE_API_KEY: "change-me"
  SMTP_USERNAME: "change-me"
  SMTP_PASSWORD: "change-me"
